[theme]
base = "light"  # Keep as "light" or "dark"
backgroundColor = "#f0f2f6"  # ← Change this to control background
primaryColor = "#7e29cd" 
secondaryBackgroundColor = "#f5f5f5"
textColor = "#31333f"
font = "sans serif"
