[theme]
base = "light"  # Keep as "light" or "dark"
backgroundColor = "#ffffff"
primaryColor = "#7e29cd" 
secondaryBackgroundColor = "#ffffff"  # ← Change this to control background
textColor = "#31333f"
font = "sans serif"
