[theme]
base = "light"
primaryColor = "#7e29cd"
backgroundColor = "#f5f6f7"  # Matches your screenshot's light grey
secondaryBackgroundColor = "#ffffff"  # White for containers
textColor = "#31333f"
font = "sans serif"
